name: auth_screen
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter_svg: ^2.0.9
  flutter:
    sdk: flutter
  auto_route: ^9.3.0+1
  flutter_bloc: ^9.1.0
  dio: ^5.8.0+1
  shimmer: ^3.0.0
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - assets/images/
